### ISSUE TITLE
Returned Data Keys are Inconsistent

### ISSUE THREAD

**Issue by MosheBerman** [Orthodox-Union/zmanim-docs#1] opened 2017-01-30 21:38 UTC
The keys in the response JSON switch between camel case and snake case. For example:

> "specialShabbos":false,
>  "parsha_shabbos":"Tzav",

Some of the methods have this problem too.

**Comment by binyamin** [comment] 2018-11-06 20:13
@MosheBerman FYI, I called OU's media department, and I the fact that there is an outstanding issue is being forwarded to the appropriate person.

**Comment by blocka** [comment] 2018-11-07 04:15
@b3u this API grew out of the needs of the OU's website and was developed organically over a long period of time. It is used in many places, and changing the keys would be a major breaking change. I'm closing this issue since this is not a bug.

**Closed as completed by blocka** 2018-11-07 04:15 UTC

**Comment by binyamin** [comment] 2018-11-07 13:55
@blocka Thanks. I had thought some of the endpoints were down, but they're working now.
